### PR TITLE
Fix: Issue/34, Add: Issue/20, Add: Issue/52

### LINKED ISSUE #20: Add: Sound effects
Sound effects for shooting, taking damage, killing enemies and so forth.

### LINKED ISSUE #34: Fix: Background starfield in multiple colours
The original game has multiple colors on the stars in the star field.

### LINKED ISSUE #52: Add: Enemy collision with ship
Aliens should be able to collide with the ship and kill it.

### PR DESCRIPTION
**Pull request by ivar1309**
Resolves #34 , Resolves #20 , Resolves #52

### CODE REVIEW

**Comment by nwessman** [comment]
Resolves #34 , Resolves #20 , Resolves #52

**Review by nwessman — CHANGES_REQUESTED** [review]
Shooting sound plays when pressing space even though the ship is not allowed to shoot.

Remove unnecessary console.log

**Review by ivar1309 — COMMENTED** [review]
Fixed

**Review by nwessman — CHANGES_REQUESTED** [review]
Shooting doesnt work anymore :(

**Review by ivar1309 — COMMENTED** [review]
Fixed!

**Review by nwessman — APPROVED** [review]
Awesome

**Pull request merged**
